gray=imread('lenna_gray256.bmp');
gray_8=bitget(gray,8);
gray_6=bitget(gray,6);
gray_7=bitget(gray,7);
woman=imread('FotoJet.bmp');
woman_to_binary=im2bw(woman);
gray_set=bitset(gray,1,woman_to_binary);
gray_set_8=bitset(gray,8,woman_to_binary);
gray_get_8=bitget(gray_set_8,8);
gray_get_1=bitget(gray_set,1);
subplot(221),imshow(gray),title('原始圖像');
subplot(222),imshow(logical(gray_8)),title('原始圖像的第八層');
subplot(223),imshow(gray_set_8),title('藏在第八層的資料');
subplot(224),imshow(logical(gray_get_8)),title('隱藏的圖像');
figure,%新打?一?窗口
subplot(221),imshow(gray),title('原始圖像');
subplot(222),imshow(woman_to_binary),title('要隱藏的圖像');
subplot(223),imshow(gray_set),title('隱藏在第一層的圖像');
subplot(224),imshow(logical(gray_get_1)),title('獲得隱藏的圖像');